# .github/workflows/deploy.yml

name: Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            make deploy-prod
          else
            make deploy-dev
          fi
