# .github/workflows/deploy.yml

name: Deploy Workflow

on:
  workflow_call:
    inputs:
      tfVersion :
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: |
              echo "sudo apt-get install python3-venv
              python3 -m venv my-project-env
              source my-project-env/bin/activate
              python3 -m pip install -U setuptools==57.5.0" > runtimepython.sh && chmod +x runtimepython.sh && bash runtimepython.sh
