name: "terraform-deploy of iam role with policy by using meta argument"

on:
  workflow_dispatch:
    inputs:
      names: 
        type: string
        description: terraform resources
        options: 
        - aws_iam_role.test_role
        - aws_iam_role_policy_attachment.test-attach
      message:
        required: true

jobs:
  IAM-creation-with-terraform:
    name: "TerraformIAM"
    runs-on: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: if condition
        if: github.event.inputs.names != ''
        run: echo "test is passed"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
