name: "Terraform Plan"

on:
  push:
    branches:
      - feature

jobs:
  terraform_fmt:
    name: "Runs Terraform fmt"
    runs-on: ubuntu-latest
    env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      
    - name: Terraform Validate
      id: validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform plan
      uses: hashicorp/terraform-github-actions/plan@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        bucket_name: "supraj-testing-sample-bucket"

    # - name: Sync S3
    #   uses: jakejarvis/s3-sync-action@master
    #   env:
    #     SOURCE_DIR: './src'
    #     AWS_REGION: 'us-east-1'
    #     AWS_S3_BUCKET: '[BUCKET_NAME_HERE]'
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
