# name: Approve Deployment

# on: [push]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Get Environments
#       id: get_environments
#       run: |
#         env_ids=$(curl  -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secrets.PAT }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/${{ github.repository }}/actions/secrets)
#         echo $env_ids
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target module for terraform execution'
      env:
        description: 'Target environment for terraform execution'
        required: true
        type: choice
        options: 
          - test
          - stage
          - prod
      application:
        description: 'Target application for terraform execution'
        required: true
        type: choice
        options: 
          - bootstrap
          - dataset
          - etl
          - sql
      disasterRecovery:
        required: false
        default: false
        type: boolean
jobs:
  check-bats-version:
    runs-on: ubuntu
    steps:
    -  name: test
       run: |
            if [ -n ${{ inputs.env }} && ${{ inputs.application }} == '' ]; then
              echo "hello world"
