name: "terraform-deploy of iam role with policy by using meta argument"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug
      message:
        required: true

jobs:
  IAM-creation-with-terraform:
    name: "TerraformIAM"
    runs-on: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: if condition
        if: github.event.inputs.names != ''
        run: echo "test is passed"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
