name: "Terraform Plan"
# on:
#   - pull_request
on:
  push:
    branches:
      - main

jobs:
  terraform_fmt:
    name: "Basic Terraform job"
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      
#     - name: terraform installtion
#       uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0

    - name: Terraform Validate
      id: validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform format check
      id: fmt
      uses: hashicorp/terraform-github-actions/fmt@v0.3.7
      continue-on-error: true

#     - name: Terraform plan
#       uses: hashicorp/terraform-github-actions/plan@v0.4.0
#       continue-on-error: true

   
#     - name: Terraform Apply
#       uses: hashicorp/terraform-github-actions/apply@v0.4.0
#       with:
#         args: '-var="bucket_name=test-supraj-githubactions"'
