name: "Terraform Plan"
on:
  - pull_request
  # push:
  #   branches:
  #     - feature

jobs:
  terraform_fmt:
    name: "Runs Terraform fmt"
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0

    - name: Terraform Validate
      id: validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7

    - name: Terraform format check
      id: fmt
      uses: hashicorp/terraform-github-actions/fmt@v0.3.7
      continue-on-error: true

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      with:
        args: '-var="bucket_name=test-supraj-githubactions"'
