# .github/workflows/main.yml

name: Main Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build code
        run: make build
      - name: Test code
        run: make test
      - name: Deploy code
        uses: ./.github/workflows/deploy.yml
        with:
          environment: production
