name: My Workflow
on: 
  workflow_dispatch:
    inputs:
      file:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v3
#      - name: Loop through items
#        run: |
#             for item in item1 item2 item3; do
#               # Call the reusable workflow
#               - name: Reusable Workflow
#                 uses: trstringer/manual-approval@v1
#                  with:
#                   secret: ${{ github.TOKEN }} 
#                   approvers: $item         
#             done
     - name: Loop over input file
       run: |
          output=""
          for item in $(cat ${{ inputs.file }}); do
            output="$output$item "
          done
          echo "::set-output name=items::$output"

#      - name: Wait for manual approval
#        uses: trstringer/manual-approval@v1
#        with:
#         secret: ${{ github.TOKEN }}
#         approvers: $approvers

#      - name: Install Dependency Packages 
#        run: | 
#               uname -a 
#               python3 -V
#               echo "sudo apt-get install python3-venv
#               python3 -m venv my-project-env
#               source my-project-env/bin/activate
#               python3 -m pip install -U setuptools==57.5.0" > runtimepython.sh && chmod +x runtimepython.sh && bash runtimepython.sh

#               cd my-project-env
#               ls
#               pwd
              
# echo "python3 -m pip install virtualenv
# virtualenv --system-site-packages --python=/tools/python/python3.6/bin/python3  venv
# source venv/bin/activate
# python3 -m pip install -U setuptools==57.5.0" > runtimepython.sh && chmod +x runtimepython.sh && bash runtimepython.sh
              
    
