# .github/workflows/main.yml

name: Main Workflow

on: push

jobs:
  call-workflow-2-in-other-repo:
    #uses: SuprajMaripeddi/terraform-github-actions/.github/workflows/deploy.yml@AWS
    uses: SuprajMaripeddi/DevOps/.github/workflows/deploy.yml@supraj
    with:
      tfVersion:  1.3.0
#   build:
#     runs-on: ubuntu-latest
#     needs:  call-workflow-2-in-other-repo
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: run verison command
#         run: |
#               echo "priniting terraform vesion"
#               echo ${{ needs.call-workflow-2-in-other-repo.outputs.terraformVersion }}
