name: 'Executing_Terraform'
run-name: ${{ github.actor }} is testing terraform execution using GitHub Actions

on:
  push:
    branches:
    - aws
 # pull_request:
env:
  environment: production
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    name: 'TerraformAuthenticationWithAzure'
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Running terraform init
      run: terraform init
      
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      
    - name: Terraform Fmt
      run: |
          ls -ll
          terraform fmt
    - name: Terraform Apply
      run: terraform apply --auto-approve

