name: Approve Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get Environments
      id: get_environments
      run: |
        env_ids=$(curl  -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/${{ github.repository }}/actions/environments | jq -r '.[].id')
        echo $env_ids
