name: pre-commit
on: push
 
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: terraform_fmt --all-files
