name: main
on: push
jobs:
#   build:
#     name: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build
#         run: echo building manual review deny
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    # Set the environment variable in a step
    - name: Set environment variable
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
          hello="AWS-GCP"
          set-env name=MY_VAR::${hello}

    # Use the environment variable in a later step
    - name: Use environment variable
      run: echo "The value of MY_VAR is $MY_VAR"

#     - name: Set environment variable
#       env:
#         MY_VAR: some value
#       run: echo "The value of MY_VAR is $MY_VAR"
#     - name: Set environment variable
# #       env:
# #         MY_VAR: some value
#       run: echo "The value of MY_VAR is $MY_VAR"

#       - uses: trstringer/manual-approval@v1
#         with:
#           secret: ${{ github.TOKEN }}
#           approvers: SuprajMaripeddi
#       - name: Deploy to production
#         run: echo deploying
