name: 'Workflow dispatch test'
on: push
jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
      - name: scdscasc
      - name: Set environment variable
        shell: bash
        run: |
              abc="hello"
              export -p abc
      - name: scdscasc
        run: |
           bbc=$abc
           echo $bbc
