on: [push]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Apply Terraform changes
      run: |
        # Set a timeout of 30 minutes for the terraform apply command
        if timeout 1m terraform apply; then
          echo "Terraform apply successful"
        else
          echo "Terraform apply failed or timed out"
          exit 1
        fi

