name: 'Wokflow github'
run-name: Testing github
on: push
jobs:
  testjob:
    runs-on: ubuntu-latest
    name: 'Workflow dispatch test'
    steps:
    - name: Set environment variable
      shell: bash
      run: |
       abc="hello"
       export abc
    - name: Print environment variable
      shell: bash
      run: |
       bbc=$abc
       echo $bbc

            
      
