name: 'Wokflow github'
run-name: Testing github
on:
  workflow_dispatch:
    inputs:
      names: 
        type: string
        description: terraform resources
jobs:
  testjob:
    runs-on: ubuntu-latest
    name: 'Workflow dispatch test'
    steps:
    - name: scdscasc
      shell: bash
      run: |
            abc=${{ github.event.inputs.names }}
            echo $abc
            
      
