name: 'Wokflow github'
run-name: Testing github
on: push
jobs:
  testjob:
    runs-on: ubuntu-latest
    name: 'Workflow dispatch test'
    steps:
    - name: scdscasc
      shell: bash
      run: |
            abc="hello"
    - name: scdscasc
      shell: bash
      run: |
            bbc=${abc}
            echo $bbc
            
      
