name: main
on: push
jobs:
#   build:
#     name: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build
#         run: echo building manual review deny
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variable
      env:
        MY_VAR: some value
      run: echo "The value of MY_VAR is $MY_VAR"

#       - uses: trstringer/manual-approval@v1
#         with:
#           secret: ${{ github.TOKEN }}
#           approvers: SuprajMaripeddi
#       - name: Deploy to production
#         run: echo deploying
