name: main
on: push
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true    
    steps:
    # Set the environment variable in a step
    - uses: actions/checkout@v3
    - name: Set environment variable
      run: |
          hello="AWS"
          echo "::set-env name=MY_VAR::${hello}"
    - name: Set environment variable new
      run: |
            echo $MY_VAR
            echo "#############"

    - name: Coverting Optum yaml to JSON
      # env:
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: |
          pip install pyyaml
          cat <<EOF >convert.py
          #!/usr/bin/env python3
          import yaml
          import json
          with open('sample.yaml', 'r') as file:
              configuration = yaml.safe_load(file)
          with open('sample.json', 'w') as json_file:
              json.dump(configuration, json_file)
          output = json.dumps(json.load(open('sample.json')), indent=2)
          EOF
          python convert.py
          data=$(cat sample.json | jq -r '.') 
          echo $data
          echo "::set-env name=JSON_DATA::${data}"
          echo $JSON_DATA
