name: main
on: push
jobs:
  deploy:
    env: 
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: deploy
    runs-on: ubuntu-latest
    steps:
    # Set the environment variable in a step
    - name: Set environment variable

      run: |
          hello="AWS-GCP"
          set-env name=MY_VAR::${hello}
    # Use the environment variable in a later step
    - name: Use environment variable
      run: echo "The value of MY_VAR is $MY_VAR"
